config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'

  resources :trains
  resources :railway_stations
  resources :routes
  resources :carriages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carriage.rb
class Carriage < ApplicationRecord
  belongs_to :train 
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
  has_many :trains, foreign_key: :current_station_id
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes

  validates :name, presence: true
end

app/models/railway_stations_route.rb
class RailwayStationsRoute < ApplicationRecord
  belongs_to :railway_station
  belongs_to :route
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :trains
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes

  validates :name, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :train
  belongs_to :user
  belongs_to :start_station, class_name: 'RailwayStation'
  belongs_to :end_station, class_name: 'RailwayStation'
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :route
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  has_many :tickets
  has_many :carriages

  validates :number, presence: true

  def count_carriages(c_type)
    self.carriages.where(c_type: c_type).count
  end

  def count_top_seats(c_type)
    self.carriages.where(c_type: c_type).sum('top_seats')
  end

  def count_bottom_seats(c_type)
    self.carriages.where(c_type: c_type).sum('bottom_seats')
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carriages_controller.rb
class CarriagesController < ApplicationController
  before_action :set_carriage, only: [:show, :edit, :update, :destroy]

  def index
    @carriages = Carriage.all
  end

  def show
  end

  def new
    @carriage = Carriage.new
  end

  def edit
  end

  def create
    @carriage = Carriage.new(carriage_params)

    if @carriage.save
      redirect_to @carriage
    else
      render :new
    end
  end

  def update
    if @carriage.update(carriage_params)
      redirect_to @carriage
    else
      render :edit
    end
  end

  def destroy
    @carriage.destroy

    redirect_to carriages_path
  end

  private

  def set_carriage
    @carriage = Carriage.find(params[:id])
  end

  def carriage_params
    params.require(:carriage).permit(:train_id, :c_type, :top_seats, :bottom_seats)
  end
end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: [:show, :edit, :update, :destroy]

  def index
    @railway_stations = RailwayStation.all
  end

  def show
  end

  def new
    @railway_station = RailwayStation.new
  end

 
  def edit
  end
 
  def create
    @railway_station = RailwayStation.new(railway_station_params)

    if @railway_station.save
      redirect_to @railway_station
    else
      render :new
    end
  end
  
  def update
    if @railway_station.update(railway_station_params)
      redirect_to @railway_station
    else
      render :edit
    end
  end
  
  def destroy
    @railway_station.destroy
      redirect_to railway_stations_url
  end

  private

  def set_railway_station
    @railway_station = RailwayStation.find(params[:id])
  end

  def railway_station_params
    params.require(:railway_station).permit(:name)
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def edit
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy

    redirect_to routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]
  
  def index
    @trains = Train.all
  end

  def show
  end
 
  def new
    @train = Train.new
  end
  
  def edit
  end
  
  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train
    else
      render :new
    end
  end
  
  def update
    if @train.update(train_params)
      redirect_to @train
    else
      render :edit
    end
  end
  
  def destroy
    @train.destroy
    redirect_to trains_url
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_station_id, :route_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carriages_helper.rb
module CarriagesHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carriages/_carriage.html.erb
<tr>
  <td><%= carriage.c_type %></td>
  <td><%= link_to 'Показать', carriage %></td>
  <td><%= link_to 'Редактировать', edit_carriage_path(carriage) %></td>
  <td><%= link_to 'Удалить', carriage, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/carriages/_form.html.erb
<%= form_for(@carriage) do |f| %>
  <%= render 'common/errors', resource: @carriage %>
  
  <div class="field">
    <%= f.label :route, "Поезд" %>
    <%= f.collection_select :train_id, Train.all, :id, :number %>
  </div>  

  <div class="field"> 
    <%= f.label :c_type, "Плацкартный" %>    
    <%= f.radio_button :c_type, "Плацкартный" %>
    <%= f.label :c_type, "Купейный" %>    
    <%= f.radio_button :c_type, "Купейный" %>    
  </div>

  <div class="field">
    <%= f.label :top_seats, 'Количество верхних мест' %>
    <%= f.number_field :top_seats %>
  </div>

  <div class="field">
    <%= f.label :bottom_seats, 'Количество нижних мест' %>
    <%= f.number_field :bottom_seats %>
  </div>

  <div class="actions">
    <%= f.submit "#{ @carriage.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
  
<% end %>

app/views/carriages/edit.html.erb
<h1>Редактирование вагонов</h1>

<%= render 'form', carriage: @carriage %>

<%= link_to 'Назад', carriages_path %>

app/views/carriages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Вагоны</h1>

<table>
  <thead>
    <tr>
      <th>Тип вагона</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @carriages %>
  </tbody>
</table>

<br>

<%= link_to 'Создать', new_carriage_path %>

app/views/carriages/new.html.erb
<h1>Создать новый вагон</h1>

<%= render 'form', carriage: @carriage %>

<%= link_to 'Назад', carriages_path %>

app/views/carriages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Тип вагона:</strong>
  <%= @carriage.c_type %>
</p>

<p>
  <strong>Присоединен к поезду:</strong>
  <%= @carriage.train.number %>
</p>

<p>
  <strong>Мест верхних:</strong>
  <%= @carriage.top_seats %>
</p>

<p>
  <strong>Мест нижних:</strong>
  <%= @carriage.bottom_seats %>
</p>


<%= link_to 'Редактировать', edit_carriage_path(@carriage) %> |
<%= link_to 'Назад', carriages_path %>

app/views/common/_errors.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(resource.errors.count, "error") %></h2>

    <ul>
    <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <footer>
      <p>(c) 2017 Ведель Анастасия. Учебный проект в <a href="http://thinknetica.com">онлайн-школе Thinknetica</a>.</p>
    </footer>
  </body>
</html>

app/views/railway_stations/_form.html.erb
<%= form_for(@railway_station) do |f| %>
  <%= render 'common/errors', resource: @railway_station %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit "#{ @railway_station.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/railway_stations/_railway_station.html.erb
<tr>
  <td><%= railway_station.name %></td>
  <td><%= link_to 'Показать', railway_station %></td>
  <td><%= link_to 'Редактировать', edit_railway_station_path(railway_station) %></td>
  <td><%= link_to 'Удалить', railway_station, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/railway_stations/edit.html.erb
<h1>Редактирование станций</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Показать', @railway_station %> |
<%= link_to 'Назад', railway_stations_path %>

app/views/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Станции</h1>

<table>
  <thead>
    <tr>
      <th>Название</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @railway_stations %>
  </tbody>
</table>

<br>

<%= link_to 'Создать', new_railway_station_path %>

app/views/railway_stations/new.html.erb
<h1>Создать новую станцию</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Назад', railway_stations_path %>

app/views/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @railway_station.name %>
</p>

<%= link_to 'Редактировать', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Назад', railway_stations_path %>

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <%= render 'common/errors', resource: @route %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
		<%= f.label :railway_station_ids, "Список станций" %>
		<%= f.collection_select :railway_station_ids, RailwayStation.all, :id, :name, {}, { multiple: true }  %>
	</div>

  <div class="actions">
    <%= f.submit "#{ @route.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/routes/_route.html.erb
<tr>
  <td><%= route.name %></td>
  <td><%= link_to 'Показать', route %></td>
  <td><%= link_to 'Редактировать', edit_route_path(route) %></td>
  <td><%= link_to 'Удалить', route, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/routes/edit.html.erb
<h1>Редактирование маршрута</h1>

<%= render 'form', route: @route %>

<%= link_to 'Показать', @route %> |
<%= link_to 'Назад', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Маршруты</h1>

<table>
  <thead>
    <tr>
      <th>Название</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @routes%>
  </tbody>
</table>

<br>

<%= link_to 'Создать', new_route_path %>

app/views/routes/new.html.erb
<h1>Создать новый маршрут</h1>

<%= render 'form', route: @route %>

<%= link_to 'Назад', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @route.name %>
</p>
<p>
  <strong>Поезда на маршруте:</strong>
  <% if @route.trains.empty? %>
    Поездов нет
  <% else %>
    <ul>
      <% @route.trains.each do |train| %>
        <li><%= train.number %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<p>
  <strong>Станции на маршруте:</strong>
  <% if @route.railway_stations.empty? %>
    Станций нет
  <% else %>
    <ul>
      <% @route.railway_stations.each do |station| %>
        <li><%= station.name %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<%= link_to 'Редактировать', edit_route_path(@route) %> |
<%= link_to 'Назад', routes_path %>

app/views/trains/_form.html.erb
<%= form_for(@train) do |f| %>
  <%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= f.label :number %>
    <%= f.number_field :number %>
  </div>

  <div class="field">
    <%= f.label :current_station, "Текущая станция" %>
    <%= f.collection_select :current_station_id, RailwayStation.all, :id, :name %>
  </div>


  <div class="field">
    <%= f.label :route, "Маршрут"%>
    <%= f.collection_select :route_id, Route.all, :id, :name %>
  </div>

  <div class="actions">
    <%= f.submit "#{ @train.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Показать', train %></td>
  <td><%= link_to 'Редактировать', edit_train_path(train) %></td>
  <td><%= link_to 'Удалить', train, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/trains/edit.html.erb
<h1>Редактирование поезда</h1>

<%= render 'form', train: @train %>

<%= link_to 'Показать', @train %> |
<%= link_to 'Назад', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Поезда</h1>

<table>
  <thead>
    <tr>
      <th>Номер</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains%>
  </tbody>
</table>

<br>

<%= link_to 'Создать', new_train_path %>

app/views/trains/new.html.erb
<h1>Создать новый поезд</h1>

<%= render 'form', train: @train %>

<%= link_to 'Назад', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Номер:</strong>
  <%= @train.number %>
</p>
<p>
  <strong>Маршрут:</strong>
  <% if @train.route.present? %>
    <%= @train.route.name %>
  <% else %>
    Не назначен
  <% end %>
</p>

<p>
  <strong>Количество плацкартных вагонов:</strong>
  <%= @train.count_carriages('economy') %>
</p>

<p>
  <strong>Количество купейных вагонов:</strong>
  <%= @train.count_carriages('coupe') %>
</p>

<p>
  <strong>Количество нижних мест в купейных вагонах:</strong>
  <%= @train.count_bottom_seats('coupe') %>
</p>

<p>
  <strong>Количество верхних мест в купейных вагонах:</strong>
  <%= @train.count_bottom_seats('coupe') %>
</p>

<p>
  <strong>Количество нижних мест в плацкартных вагонах:</strong>
  <%= @train.count_bottom_seats('economy') %>
</p>

<p>
  <strong>Количество верхних мест в плацкартных вагонах:</strong>
  <%= @train.count_bottom_seats('economy') %>
</p>

<%= link_to 'Редактировать', edit_train_path(@train) %> |
<%= link_to 'Назад', trains_path %>

app/views/welcome/index.html.erb
<h1>Railway Stations</h1>

<%= link_to 'Станции', railway_stations_path %>
<%= link_to 'Поезда', trains_path %>
<%= link_to 'Маршруты', routes_path %>
<%= link_to 'Вагоны', carriages_path %>